[package]
name = "rift"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = { version = "0.14.0", default-features = false, features = ["use_alloc"] }
paste = "1.0.15"
portal-pc-asm-common = { version = "0.1.0", features = ["alloc"] }
portal-pc-waffle = "0.5.4"
rv-asm = "0.2.1"
